### ISSUE TITLE
How this is different from default /metrics of keycloak?

### ISSUE THREAD

**Issue by thamaraiselvam** [aerogear/keycloak-metrics-spi#113]
We are thinking of building monitoring dashboard for keycloak and we found this repo, and how this is better than default metrics?

**Comment by pb82** [comment]
@thamaraiselvam As far as i'm aware, Keycloak still doesn't provide metrics about internal events involving users, logins, errors, registrations nor metrics about request durations.

That's why we started this extension, not sure if the latest Keycloak releases offer more in terms of built-in metrics.

**Comment by pb82** [comment]
Closing this for now, if you have additional questions or issues, please create a new issue.
