### ISSUE TITLE
Provider no longer works on redhat-sso 7.3

### ISSUE THREAD

**Issue by 6869dan** [aerogear/keycloak-metrics-spi#23]
## Description
Firstly, thanks for this provider - have been happily using this for our current keycloak/redhat-sso implementation. However, following an upgrade the keycloak specific metrics no longer work on redhat-sso 7.3 (RHEL branded implementation of keycloak)

## Expected Behavior
Metrics such as keycloak_failed_login_attempts should record failed logins as per previous version (7.2)

## Actual Behavior
jvm metrics are recorded as before but no keycloak metrics are recorded under  /auth/realms/master/metrics as previously

## Environment

* Operating system: Centos 7
* OpenShift versions: kubernetes 1.10
* Project Versions: 

## Steps to reproduce
Deploy redhat-sso 7.3, observe keycloak metrics such as logins and failed logins no longer reflected in metrics endpoint.

Appreciate this is most likely due to a divergence from keycloak standards by redhat but wanted to raise for awareness.

**Comment by aliok** [comment]
hi @6869dan 
Thanks for reporting this bug.

Even though I haven't tried it yet, I think it is related to a known problem we're aware of which will be fixed with https://trello.com/c/Qmr4E3Ql/229-8-metrics-grafana-as-a-developer-i-want-a-sync-service-metrics-dashboard-grafana-such-that-i-can-have-a-summary-view-of-sync-cli

I will keep you posted.

**Comment by pb82** [comment]
Looks like this could be fixed with https://github.com/aerogear/keycloak-metrics-spi/pull/24

**Comment by pb82** [comment]
@6869dan Can you please try again with the latest commit (master branch)? I believe @Jdourd 's fix could resolve your issue (it's possible that the SPI raised a NPE on those events and thus wasn't able to record them).

**Comment by aliok** [comment]
Might be fixed with #25 as well.

Created a release here: https://github.com/aerogear/keycloak-metrics-spi/releases/tag/1.0.0

Could you give the jar in that release a try?

**Comment by 6869dan** [comment]
Thx all, I'll give the latest release a try and confirm!

**Comment by 6869dan** [comment]
Thx a lot @pb82  & @aliok - can confirm this is working again using your latest SPI jar file and rhsso-7.3.
Many thanks!

**Comment by pb82** [comment]
Thanks for verifying this @6869dan . I think we can close this issue now.

**Comment by onnder** [comment]
Hi. I have raised similar issue https://github.com/aerogear/keycloak-metrics-spi/issues/61. @6869dan please can you confirm that your RHSSO environment is still working correctly since your issue was fixed? It would be very helpful if you can provide your (functional) combination of redhat sso version/patch and metrics-listener SPI build. Thank you.

**Comment by aliok** [comment]
cc @wei-lee @grdryn

**Comment by aliok** [comment]
cc @wei-lee @grdryn @pb82
